version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  hotelaria:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/usr/src/app
