version: "3.8"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  hotelaria:
    build:
      context: .
      dockerfile: Dockerfile_production
    container_name: api
    environment:
      DB_SCHEMA: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db
      JWT_SECRET: "secret123"
      JWT_EXPIRATION: 1800
    depends_on:
      - db
    ports:
      - "80:3000"
    volumes:
      - ./src/:/usr/src/app
